name: Third Workflow
on: push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: List and Copy Repo
        run: |
          pwd
          ls -la
      - uses: actions/checkout@v7
      - name: List
        run: |
          pwd
          ls -la
